### ISSUE TITLE
speed improvement consideration

### ISSUE THREAD

**Issue by c1c2c3c4c** [callummoffat/Rochambeau#1]
The first check of a if else statement should be for one of the most likely events. Each check is really a jump if not equal statment. So it's a compare and then a change of the pointer. This takes a few fractions of a millisecond so it's no big deal if you are running a single command. However if your talking about a server sequencing a genome this adds up fast, so it's always best to practice keeping the time to a minimum. 

It's a solid program though, keep up the work. 🤓

**Comment by callummoffat** [comment]
I agree. In this context, however, it is necessary to ensure the two objects are not equal (i.e. the round was a draw) before checking for a winner/loser. The way I learned to play paper/scissors/rock, a draw results in neither side gaining any points, so it is necessary to suffer the minor performance hit in order to ensure the game is played by the rules.

As you said, it's a pretty solid program despite that though. I'd like to meet the guy who could find a way to bamboozle this little wonder into letting you cheat (without modifying the source).

**Comment by c1c2c3c4c** [comment]
One way should be:
               if (playersChoice < computerChoice \ not sure if < matched your logic.
.                               cout << Constants::getRoundLoseText(playerName);{
                computerScore++;
                }
        else {
            if (playersChoice != computerChoice){ \ we know it's not < so it it's not = it is >. Same as an "and" operation which is only 1cost assuming the compiler is decent.
                cout << Constants::getRoundWinText(playerName);
                playerScore++;
            }
.                        else{
.                               cout << Constants::DrawMessage;
.                       }
        }

**Comment by c1c2c3c4c** [comment]
But honestly for this type of application it's a perfectly fine solution, and it's better than I wrote when I was learning

**Comment by callummoffat** [comment]
Thanks. I believe readability is preferable in this instance. For some things, it would be certainly be better to favor performance over an easy to follow application. 

In this case, I believe my code is simpler to follow, even if yours is faster. Since this is a practice application, I'm relatively happy with my current solution.

I'll probably test to see if the performance enhancement is enough to justify using your solution, though.

**Comment by callummoffat** [comment]
I've integrated your suggestion into the app. The performance enhancements incurred by this change don't impact the solidity of the code in any way, so I thought it worth implementing them.

**Comment by c1c2c3c4c** [comment]
It wouldn't justify it, this was just to help you as you continue. We are talking about really small average time savings on an application like this.

I also have an error in my statement, it's a nand operation. An and would actually be 2cost because nand is the simpler logic gate on a cpu. A and gate is thus a nand gate and an inverter.

**Comment by callummoffat** [comment]
Thanks for the help! It'll definitely be useful for more complex programs. Here, it only incurs a minimal performance improvement, but it's worth implementing simply to learn how to optimize C++ OOP code.
